let shopItemsData = [{
        id: "jfhgbvnscs",
        name: "Maize",
        price: 230,
        desc: "Farm seeds hybrid maize corn",
        img: "./images/maize3.jpg",
    },
    {
        id: "ioytrhndcv",
        name: "250gm seeds",
        price: 240,
        desc: "Tomato seeds, super sweet",
        img: "./images/tomato.jpg",
    },
    {
        id: "wuefbncxbsn",
        name: "Beans",
        price: 140,
        desc: "French beans seeds",
        img: "./images/beans.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Dry seeds",
        price: 240,
        desc: "Dry bean seed",
        img: "./images/beans3.jpg",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Animal feeds",
        price: 5850,
        desc: "Pig Starter",
        img: "./images/anim.jpg"

    },
    {
        id: "iuertrywebncdjksadjk",
        name: "50kg bag",
        price: 4000,
        desc: "planting fertilizer-rich in nitrogen",
        img: "./images/fert.jpg",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "50kg fertiliser",
        price: 4500,
        desc: "Compost enriches soil",
        img: "./images/fert1.jpg",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "DAP 50kg bag  ",
        price: 5200,
        desc: "Support the plants stem",
        img: "./images/fert2.jpg",
    },
    {
        id: "cbvxbcvsceldk",
        name: "Growers",
        price: 3600,
        desc: "Growers mash",
        img: "./images/chick1.jpg",
    },
    {
        id: "oiopijmjkhuihb",
        name: "Starter",
        price: 2100,
        desc: "Fast Gro",
        img: "./images/chick3.jpg",
    },
    {
        id: "oiopijewyiohbjhib",
        name: "Chickmash 50kg ",
        price: 3200,
        desc: "Chick and Duckling Mash",
        img: "./images/chick.jpg",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "Finisher",
        price: 3500,
        desc: "Fast gro- Finisher Pellets",
        img: "./images/chick2.jpg",
    },
];